### ISSUE TITLE
sync with upstream

### ISSUE THREAD

**Issue by wnleao** [javascript-tutorial/pt.javascript.info#126]

**Comment by fsdude** [comment]
As novas traduções devem ser feitas seguindo o atual 'pt.javascript.info' repo ou o atual 'en.javascript.info'?

**Comment by fsdude** [comment]
should I try to make a branch with the synchronized content or is someone already working on it?

**Comment by jonnathan-ls** [comment]
@wnleao 

It is not possible to understand what is expected of this issue, there is no description about the details. I will close the request and if you still receive this notification and want to open a new demand detailing what you need, feel free. ❤️

**Comment by jonnathan-ls** [comment]
@wnleao

It is not possible to understand what is expected of this issue, there is no description about the details. I will close the request and if you still receive this notification and want to open a new demand detailing what you need, feel free. ❤️
