### ISSUE TITLE
Status review for unfinished articles

### ISSUE THREAD

**Issue by Peruibeloko** [javascript-tutorial/pt.javascript.info#416]
I went over the translation checklist and classified each item in one of three categories:

- **Unchecked**: Item is present in the master branch but not marked as done
- **Abandoned**: Item has work present on a fork but the PR is either closed or absent
- **Untouched**: Item is assigned to someone but it wasn't worked on at all

And this is the current status:

| Item                                   | Status                                         |
| -------------------------------------- | ---------------------------------------------- |
| Basic operators, math                  | Unchecked (#217, #412)                         |
| Loops: while and for                   | Abandoned (#50)                                |
| Functions                              | Untouched                                      |
| Object references and copying          | Unchecked                                      |
| Symbol type                            | Unchecked                                      |
| Numbers                                | Untouched (under @rnrnshn)                     |
| WeakMap and WeakSet                    | Untouched (under @wnleao)                      |
| Object.keys, values, entries           | Abandoned                                      |
| Destructuring assignment               | Untouched                                      |
| Date and time                          | Untouched                                      |
| JSON methods, toJSON                   | Abandoned (#185)                               |
| Recursion and stack                    | Abandoned                                      |
| Rest parameters and spread syntax      | Untouched                                      |
| Variable scope, closure                | Untouched                                      |
| The old "var"                          | Untouched                                      |
| Scheduling: setTimeout and setInterval | Untouched                                      |
| Function binding                       | Untouched                                      |
| Property getters and setters           | Abandoned                                      |
| Class inheritance                      | Untouched                                      |
| Static properties and methods          | Untouched                                      |
| Extending built-in classes             | Abandoned (#411)                               |
| Error handling, "try...catch"          | Untouched                                      |
| Custom errors, extending Error         | Abandoned                                      |
| Introduction: callbacks                | Abandoned                                      |
| Promise                                | Untouched                                      |
| Error handling with promises           | Untouched (under @wnleao)                      |
| Promise API                            | Untouched                                      |
| Promisification                        | Untouched (under @wnleao)                      |
| Microtasks                             | Untouched (under @wnleao)                      |
| Async/await                            | Untouched                                      |
| Modules, introduction                  | Untouched                                      |
| Currying                               | Untouched                                      |
| Browser environment, specs             | Abandoned                                      |
| DOM tree                               | Abandoned                                      |
| Walking the DOM                        | Abandoned                                      |
| Attributes                             | Review pending (broken mention @denis-rossati) |
| Introduction to browser events         | Untouched (broken mention to @cesarkohl)       |
| Form properties and methods            | Untouched (broken mention to @recalderon)      |
| Fetch                                  | Abandoned (broken mention to @vitorinoaraujo)  |
| Bezier curve                           | Abandoned (broken mention to @lucastrvsn)      |
| JavaScript animations                  | Abandoned (broken mention to @karlasamantha)   |
| Template element                       | Untouched (broken mention to @HakaCode)        |

We can solve some of these problems as such:
- Abandoned articles can be resumed through a new PR
- Untouched articles assigned over a certain period (6 months, 1 year) can be safely unassigned and reopened for translation
- Unchecked articles can be safely checked for updated tracking

What does everyone think?

**Comment by odsantos** [comment]
@Peruibeloko I agree but we probably need to be sure that Untouched topics have no PR, so three months might also be a good waiting period. Thanks.

**Comment by Peruibeloko** [comment]
@odsantos most of the Untouched topics are months or years out of date with master. I can go over them and append the age of the assignment if you'd like

**Comment by odsantos** [comment]
@Peruibeloko no, there is no need, as long as no work is present this seems good. Thanks.

**Comment by Peruibeloko** [comment]
Glad to help, let me know if you need anything!

**Comment by HakaCode** [comment]
@Peruibeloko @odsantos 

I will arrange it as soon as possible, I had forgotten to translate, thank you for reminding me.

**Comment by Peruibeloko** [comment]
@HakaCode thanks! Just a quick reminder to keep the PR contained to the specific as article you're translating!

**Comment by HakaCode** [comment]
@Peruibeloko @odsantos I think now I just wait for it to be reviewed and accepted.

**Comment by danilolmc** [comment]
Hey guys!

About the Extending built-in classes article, I'm now just waiting a review in the #413 PR

I also translated these two articles below, but they are unchecked even thought I created their pull request with their article titles:

- Object references and copying #408  	
- Symbol type #409 

How can I mark them as checked?

**Comment by Peruibeloko** [comment]
@danilolmc I didn't include your class extension article since I remember seeing you picking it one of these days.

Marking them as done is probably restricted to either the bot or @iliakan

**Comment by danilolmc** [comment]
Great, thank you! @Peruibeloko

**Comment by jonnathan-ls** [comment]
> Abandoned articles can be resumed through a new PR

Instead of reopening the PR, we could contribute directly to it (PR number), and if the user's branch or repository is protected, then the task goes on to be reopened in a new PR, **what do you think**?

In reviews, I'm looking to contribute by adding commits directly to the user's forked repository that is associated with the PR, instead of just registering my comments for simple things, trying to speed up the merge process, instead of waiting for the user's response that may have abandoned the PR

**Comment by jonnathan-ls** [comment]
> Hey guys! 
> ... 
> How can I mark them as checked?

@danilolmc 

**My deduction**, the bot apparently did not act on the PRs because the merger was apparently carried out without following the necessary review steps (review and approval process) and perhaps because it failed to mark the PR's hash on the list due to absences in the approval and registration procedures of the task on behalf of the person.

Maintainers have the ability to update PR #1. 

I have updated the list considering the PRs have been completed.

**Comment by jonnathan-ls** [comment]
> I agree but we probably need to be sure that Untouched topics have no PR, so three months might also be a good waiting period. Thanks.

I agree with 03 months instead of 06, we need agility and evolution of this repository instead of waiting for PRs that haven't even been touched yet.

**Comment by savionascimentodev** [comment]
Hello everyone, I would really like to contribute to this repository, but I'm kind of new to open source projects, I saw that there are a lot of PRs open and after this list that @Peruibeloko  sent, it gave me a little idea, but if I want to contribute , is there anyone active I can talk to?

Note: Or I just raise a Pr and who knows, one day it will be approved.

**Comment by danilolmc** [comment]
Hey @savionascimentodev !


You can take a look at #1 issue.

Hope it can help you...

**Comment by Peruibeloko** [comment]
@savionascimentodev Seja bem-vindo mano!

O processo é bem simples:
- Escolha um capítulo para traduzir na lista da issue #1
- Comente o nome *exato* do capitulo
- Crie um fork do repositório
- Contribua!

Esse é o resumo executivo, posso te auxiliar lá no #1 diretamente, já que aqui é mais voltado para outro assunto :D

**Comment by Peruibeloko** [comment]
Vou fechar essa issue, já que conseguimos trazer atenção ao problema e movimentamos o #1
